name: Build Kernel

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/liyafe1997/kernel_xiaomi_sm8250_mod
          kernel-dir: msm-4.19
          kernel-branch: android15-lineage22-mod
          config: kona_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: legacy
          susfs: true
          android-version: 14
          aosp-clang-version: r563880c
          disable-lto: true
          anykernel3: true
          extra-cmd: |
            cd $GITHUB_WORKSPACE
            rm -rf kernel_workspace/kernelsu
            git clone -b legacy https://github.com/KernelSU-Next/KernelSU-Next.git kernel_workspace/kernelsu
            cd $GITHUB_WORKSPACE/device_kernel
            git checkout $(git log --grep="4.19.191" --format="%H" -n 1) || true
            echo "CONFIG_KPROBES=n" >> arch/arm64/configs/vendor/kona_defconfig
            echo "CONFIG_HAVE_KPROBES=n" >> arch/arm64/configs/vendor/kona_defconfig
            echo "CONFIG_DEBUG_FS=n" >> arch/arm64/configs/vendor/kona_defconfig
            cat arch/arm64/configs/vendor/xiaomi/pipa.config >> arch/arm64/configs/vendor/kona_defconfig
            
